services:
  core:
    image: ci
    build:
      args:
        - BASE_IMAGE=ubuntu:20.04
        - PYTHON_VERSION=3.12
        - RUN_POETRY_INSTALL_AT_BUILD_TIME=true
        - PROJECT_NAME=${PROJECT_NAME_ENV}
      context: ../../
      dockerfile: environments/Dockerfile
    tty: true
    volumes:
        - ../../:/home/challenger/${PROJECT_NAME_ENV}
        # The following setting is to avoid overwriting the host/container's .venv
        # i.e., the host .venv do not affect the container, and vice versa
        - /home/${USER-challenger}/${PROJECT_NAME_ENV}/.venv