services:
  core:
    image: ci
    build:
      args:
        - BASE_IMAGE=ubuntu:20.04
        - PYTHON_VERSION=3.12
        - RUN_POETRY_INSTALL_AT_BUILD_TIME=true
        - PROJECT_NAME=${PROJECT_NAME_ENV}
      context: ../../
      dockerfile: environments/Dockerfile
    tty: true
    volumes:
        - ../../:/home/${USER-challenger}/${PROJECT_NAME_ENV}
        # The following setting is to avoid overwriting the container's .venv
        # do not update .venv in the host machine.
        # "rm -r .venv" is recommended before running the container.
        - /home/${USER-challenger}/${PROJECT_NAME_ENV}/.venv